### ISSUE TITLE
Make it possible to easily start a go-nitro node hyrdated with rich data

### ISSUE THREAD

**Issue by geoknee** [statechannels/nitro-gui#10]
We can generate a DB snapshot manually or via an integration test with several nodes, and then simply place this in the correct dir when starting a node in `-durablestore` mode.

When we have that situation, it should let us hydrate the dashboard / UI from a single client with a single command. That's lower friction for devs working on the UI.

**Comment by geoknee** [comment]
I attempted to generate a snapshot like this today. Steps:

Tile 5 terminal panels:
1. `docker run -it -d -p 8545:8545 --name hardhat hardhat && docker logs --follow hardhat`
2. in `go-nitro` dir:`rm -rf ./data` then `go run . -usedurablestore -deploycontracts` (blow away any old stores and start a node with default ports)
3. in `go-nitro` dir: `go run . -usedurablestore -msgport 3006 -rpcport 4006 -pk 0aca28ba64679f63d71e671ab4dbb32aaa212d4789988e6ca47da47601c18fe2` (has address 0xB2B22ec3889d11f2ddb1A1Db11e80D20EF367c01)
 4. in `go-nitro` dir: `go run . -usedurablestore -msgport 3007 -rpcport 4007 -pk febb3b74b0b52d0976f6571d555f4ac8b91c308dfa25c7b58d1e6a7c3f50c781` (has address 0x111A00868581f73AB42FEEF67D235Ca09ca1E8db)
 5. In `nitro-rpc-client` dir: `yarn start direct-fund 0x111A00868581f73AB42FEEF67D235Ca09ca1E8db -p 4005` (prompt Alice to connect to Irene)


I'm currently stuck here, though, because direct fund never completes. Irene doesn't seem to see the chain event.

**Comment by lalexgap** [comment]
> I attempted to generate a snapshot like this today. Steps:
> 
> Tile 5 terminal panels:
> 
>     1. `docker run -it -d -p 8545:8545 --name hardhat hardhat && docker logs --follow hardhat`
> 
>     2. in `go-nitro` dir:`rm -rf ./data` then `go run . -usedurablestore -deploycontracts` (blow away any old stores and start a node with default ports)
> 
>     3. in `go-nitro` dir: `go run . -usedurablestore -msgport 3006 -rpcport 4006 -pk 0aca28ba64679f63d71e671ab4dbb32aaa212d4789988e6ca47da47601c18fe2` (has address 0xB2B22ec3889d11f2ddb1A1Db11e80D20EF367c01)
> 
>     4. in `go-nitro` dir: `go run . -usedurablestore -msgport 3007 -rpcport 4007 -pk febb3b74b0b52d0976f6571d555f4ac8b91c308dfa25c7b58d1e6a7c3f50c781` (has address 0x111A00868581f73AB42FEEF67D235Ca09ca1E8db)
> 
>     5. In `nitro-rpc-client` dir: `yarn start direct-fund 0x111A00868581f73AB42FEEF67D235Ca09ca1E8db -p 4005` (prompt Alice to connect to Irene)
> 
> 
> I'm currently stuck here, though, because direct fund never completes. Irene doesn't seem to see the chain event.

I think the underlying problem is that an RPC server would deploy a new nitro adjudicator every time it's run (with the `-deploycontracts` ) instead of using `Create2Deployer` properly to compute same address. The RPC servers started in 3) and 4) would point to the[ default naaddress](https://github.com/statechannels/go-nitro/blob/9017aa9269d0e74d7a6ce34706cd5ec11240674b/main.go#L38) which be a separate adjucatior from the one deployed in 2)

I've updated this in https://github.com/statechannels/go-nitro/pull/1259 so we properly use the `Create2Deployer`

**Comment by lalexgap** [comment]
@kerzhner this might be useful for you (at least until I get a decent test script going 🙂)

This gives a brief description how to:
- spin up multiple RPC servers
- Generate data by interacting with them via the `nitro-rpc-client`
- Export or import the data generated by the RPC servers.

Note: This is written using the `autodeploy` flag from an [open pull request](https://github.com/statechannels/go-nitro/pull/1259). The PR fixes our use of `Create2Deployer` and simplifies configuration for spinning up an RPC server.
 
# Start up the RPC servers
We will need 4 consoles. 

## Console 1 (chain instance):
This will be our chain that all the RPC servers talk to. This must be done before starting the RPC servers! 

I'm using `foundry` to do this. Installation instructions can be found [here](https://book.getfoundry.sh/getting-started/installation) 

- `anvil --chain-id 1337`

## Console 2 (Alice RPC Server):
From `go-nitro` run:
- `go run . -autodeploy -usedurablestore`

This will start an RPC server using the default address(Alice) and listening for RPC requests on the default port of 4005.

## Console 3 (Irene RPC Server):
From  `go-nitro` run:
- `go run . -autodeploy -usedurablestore -msgport 3006 -rpcport 4006 -pk febb3b74b0b52d0976f6571d555f4ac8b91c308dfa25c7b58d1e6a7c3f50c781`

This starts an RPC server running as `0x111a00868581f73ab42feef67d235ca09ca1e8db` listening for RPC requests on port 4006.

## Console 4 (Bob RPC Server)
From `go-nitro` run:
- `go run . -autodeploy -usedurablestore -msgport 3007 -rpcport 4007 -pk 0279651921cd800ac560c21ceea27aab0107b67daf436cdd25ce84cad30159b4`

This starts an RPC server running as `0xbbb676f9cff8d242e9eac39d063848807d3d1d94` listening for RPC requests on port 4007.

Using `mdns` the RPC servers will automatically discover each other for messaging purposes. At this point we have 3 RPC servers ready to interact with.

## Creating Some Channels / Data

We'll be issuing commands to different RPC servers by specifying the RPC port we expect the server to be listening on:
- Alice's RPC server is listening on port **4005**
- Irene's RPC server is listening on port **4006**
- Bob's RPC server is listening on port **4007**


Open a new a console go to `nitro-gui/packages/nitro-rpc-client`

1. Create a ledger channel between alice and irene by running `yarn start -p 4005 direct-fund 0x111A00868581f73AB42FEEF67D235Ca09ca1E8db`
2. Create a ledger channel between irene and bob by running `yarn start -p 4006 direct-fund 0xBBB676f9cFF8D242e9eaC39D063848807d3D1D94`
3. Create a virtual channel between alice and bob (using irene as the intermediary) by running `yarn start -p 4005 virtual-fund  0xBBB676f9cFF8D242e9eaC39D063848807d3D1D94 0x111A00868581f73AB42FEEF67D235Ca09ca1E8db`
4. If desired create more virtual channels by running the command above.
5. Pay using one of the channels. Using the channel id of one the virtual channels you created  from previous step and then run `yarn start -p 4005 pay 0x7307fe839041bf15719bed54a65f042447e252d1c420848e5ff8fc1cb311ac59 1`. 


## Exporting the data

The data for the nitro RPC servers will be stored in `go-nitro/data/nitro-service`. 

From `go-nitro` run 
`tar -c -z -f basic-scenario.tar.gz  data/nitro-service`. (where `basic-scenario` is reasonable name for the data)

## Importing Data


Copy the tar file to `go-nitro`.
Run `tar -xvf basic-scenario.tar.gz`. This will extract the data files to `go-nitro/data/nitro-service`.

## Checking the data

From `nitro-gui/packages/nitro-rpc-client` you can query the data:
- Query a payment channel: `yarn start -p 4005 get-payment-channel 0x7307fe839041bf15719bed54a65f042447e252d1c420848e5ff8fc1cb311ac59`
- Query a ledger channel: `yarn start -p 4005 get-ledger-channel 0x0ef76e7362f1b25150de97712b61ad69c3423351061e9ae24d332fe2b8468b6b`

Here's the [basic-scenario.tar.gz](https://github.com/statechannels/nitro-gui/files/11410596/basic-scenario.tar.gz) I generated by running these instructions.

**Comment by lalexgap** [comment]
Closing this as we now have some scripts to handle generating data.
