### ISSUE TITLE
Create a payment channel component

### ISSUE THREAD

**Issue by NiloCK** [statechannels/nitro-gui#2]
From the general wireframe 
![image](https://user-images.githubusercontent.com/10780590/235739720-50494de6-c1a1-4479-a05f-700e7fd4ec31.png)

Create a component for displaying status / balances of a running payment channel:

![image](https://user-images.githubusercontent.com/10780590/235739638-596d7054-a018-4fad-88b8-4a5c99033b1d.png)

Requirements: supplied props should look approximately like

```
type PaymentChannelComponentProps = {
  channelID: string;
  counterparty: string; // address for now - can abstract to something richer later
  capacity: bigint; // total value locked in channel
  myBalance: bigint; // balance of the viewing participant
  status: 'prefund' | 'running' | 'unresponsive-peer' | 'under-challenge';
}
```

**Comment by geoknee** [comment]
The reference for the data to hydrate props is here https://github.com/statechannels/go-nitro/blob/6268bbb73061f7bba59826d3abb5e7bab88f7a3d/client/query/types.go#L29

**Comment by geoknee** [comment]
[Update] There should be no buttons, and `counterparty` and `status` should be displayed like so: 


![Screenshot 2023-05-26 at 10 33 38](https://github.com/statechannels/nitro-gui/assets/1833419/fe546e9e-249b-4ab8-8fb6-dbda845f45aa)



Extension: we could use blockies here https://github.com/MyCryptoHQ/ethereum-blockies-base64
